# Generated by Django 2.2.19 on 2021-09-02 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='наименование')),
                ('slug', models.SlugField(allow_unicode=True, max_length=30, unique=True, verbose_name='слаг')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'Справочник',
                'verbose_name_plural': 'Справочники',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='версия справочника')),
                ('start_date', models.DateField(verbose_name='дата начала действия')),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='api.Guide')),
            ],
            options={
                'verbose_name': 'версия',
                'verbose_name_plural': 'версии',
                'ordering': ('-start_date',),
            },
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='код')),
                ('value', models.CharField(max_length=200, verbose_name='значение')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='api.Version')),
            ],
            options={
                'verbose_name': 'элемент',
                'verbose_name_plural': 'элементы',
                'ordering': ('code',),
            },
        ),
        migrations.AddConstraint(
            model_name='version',
            constraint=models.UniqueConstraint(fields=('guide', 'name'), name='unique_guide_version'),
        ),
        migrations.AddConstraint(
            model_name='element',
            constraint=models.UniqueConstraint(fields=('code', 'value'), name='unique_elements_code_value'),
        ),
    ]
