# Generated by Django 2.2.19 on 2021-09-04 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element',
            name='version',
        ),
        migrations.AddField(
            model_name='element',
            name='versions',
            field=models.ManyToManyField(related_name='elements', to='api.Version', verbose_name='версии'),
        ),
    ]
