# Generated by Django 2.2.19 on 2021-09-11 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='element',
            name='unique_elements_code_value',
        ),
        migrations.AlterField(
            model_name='element',
            name='code',
            field=models.CharField(db_index=True, max_length=50, verbose_name='код'),
        ),
        migrations.AlterField(
            model_name='element',
            name='value',
            field=models.CharField(max_length=100, verbose_name='значение'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='short_title',
            field=models.CharField(max_length=50, unique=True, verbose_name='короткое наименование'),
        ),
        migrations.AddConstraint(
            model_name='element',
            constraint=models.UniqueConstraint(fields=('code', 'value'), name='unique_code_value'),
        ),
    ]
