# Generated by Django 2.2.19 on 2021-09-11 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210911_1851'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='element',
            constraint=models.UniqueConstraint(fields=('version', 'code'), name='unique_code_in_version'),
        ),
        migrations.AddConstraint(
            model_name='element',
            constraint=models.UniqueConstraint(fields=('version', 'value'), name='unique_value_in_version'),
        ),
    ]
