# Generated by Django 2.2.19 on 2021-09-11 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210911_0714'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='elementinversion',
            name='element_in_version_constraint',
        ),
    ]
