# Generated by Django 2.2.19 on 2021-09-04 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210904_1301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='element',
            old_name='versions',
            new_name='version',
        ),
    ]
