# Generated by Django 2.2.19 on 2021-09-05 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210905_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='value',
            field=models.CharField(max_length=100, verbose_name='значение'),
        ),
    ]
