# Generated by Django 2.2.19 on 2021-09-11 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210911_1856'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='element',
            name='unique_code_value',
        ),
    ]
