# Generated by Django 2.2.19 on 2021-09-11 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210911_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='api.Version', verbose_name='версия'),
        ),
        migrations.AlterField(
            model_name='version',
            name='guide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='api.Guide', verbose_name='справочник'),
        ),
    ]
